### ISSUE TITLE
paypal crashing the app on android

### ISSUE THREAD

**Issue by Josefnm** [primer-io/primer-sdk-react-native#160]
JSONException: Value null at shippingAddress of type org.json.JSONObject$1 cannot be converted to JSONObject

Primer version: 2.14.4
react native 0.66.4

Stopped working without making any changes. Happens when the vault flow is completed.

**Comment by semirp** [comment]
@Josefnm Thanks for the report. We will get back to you ASAP.

**Comment by semirp** [comment]
@Josefnm This had been fixed. No update of the SDK is required.

**Comment by Josefnm** [comment]
But we need to update to the latest version of your sdk, right? As the bug is still happening in production for us.
