### ISSUE TITLE
Bugs with android (v0.15.4)

### ISSUE THREAD

**Issue by Josefnm** [primer-io/primer-sdk-react-native#55]
1. It gives an intent error when using showPaymentMethod. The issue is that "vault" and "checkout" is lowercase. This is correct for ios sdk, but android uses uppercase.

2. IOptions is typed incorrectly.
```
interface IOptions {
  isResultScreenEnabled?: boolean;
  isLoadingScreenEnabled?: boolean;
  isFullScreenEnabled?: boolean;
  is3DSOnVaultingEnabled?: boolean;
  is3DSDevelopmentModeEnabled?: boolean;
  locale?: string;
  ios?: IIosOptions;
  redirectScheme?: RedirectScheme;
}
```

redirectScheme should be nested in android.
```
interface IOptions {
  ...
  android?: {
    redirectScheme?: RedirectScheme;
  };
}  
  ```
  
3.
Listeners do not work on showPaymentMethod (onError, onVaultSuccess etc). Looks like they are simply not added.

**Comment by Josefnm** [comment]
paymentMethod: 'PAYMENT_CARD' doesn't work on android. It's supposed to be 'CARD'.

**Comment by semirp** [comment]
@Josefnm Please check on `v.0.15.8`
